# Kafka Configuration
kafka:
  bootstrap-servers: 192.168.152.131:9092
  topic: selection-topic
  group-id: stats-consumer-group

# Redis Configuration
redis:
  host: 192.168.152.131
  port: 6379
  username: octopuz_remote
  password: Octopuz@123
  database: 1

# Spark Configuration
spark:
  master: local[*]
  app-name: RealtimeSelectionStats
  driver-memory: 512m
  executor-memory: 1g
