spring:
  application:
    name: statistics-api
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 1000ms

server:
  port: ${STATISTICS_API_PORT:8082}

logging:
  level:
    com.octopuz.statisticsapi: ${LOG_LEVEL:INFO}
