spring:
  application:
    name: selection-service
  # redis
  data:
    redis:
      host: ${REDIS_HOST:192.168.152.131}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:1}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 100ms
          time-between-eviction-runs: 3000ms
  # kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST:192.168.152.131}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: 1
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${KAFKA_GROUP_ID:selection-consumer-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

server:
  port: ${SERVER_PORT:8081}


basic-service:
  url: ${BASIC_SERVICE_URL:http://localhost:8080}

logging:
  level:
    com.octopuz.selectionservice: ${LOG_LEVEL:DEBUG}
